/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IonPersonOutline: typeof import('~icons/ion/person-outline')['default']
    OrderAddresses: typeof import('./../src/components/OrderAddresses/index.vue')['default']
    OrderHeader: typeof import('./../src/components/OrderHeader/index.vue')['default']
    OrderSuplier: typeof import('../src/components/OrderSupplier/index.vue')['default']
    OrderSupplier: typeof import('./../src/components/OrderSupplier/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
